### ISSUE TITLE
App Not Opening On Android Device 

### ISSUE THREAD

**Issue by gdad-s-river** [meteor/module-todos-react#2]
I did
`npm install`
`meteor add-platform android`
`meteor run android-device`

I get this error : 

> TypeError: Can't call method on  undefined
>     at TypeError (<anonymous>)
>     at module.exports (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.defined.js:3:28)
>     at module.exports (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.to-object.js:4:17)
>     at from (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.array.from.js:12:19)
>     at exports.default (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/helpers/toConsumableArray.js:19:31)
>     at CordovaProject.run$ (/tools/cordova/project.js:207:17)
>     at tryCatch (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:72:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke](/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:334:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:105:21)
>     at tryCatch (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:72:40)
>     at invoke (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:146:20)
>     at /Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:191:11
>     at new Promise (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/core-js/library/modules/es6.promise.js:197:7)
>     at callInvokeWithMethodAndArg (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:190:16)
>     at AsyncIterator.enqueue (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:211:37)
>     at AsyncIterator.prototype.(anonymous function) [as next](/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:105:21)
>     at Object.runtime.async (/Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:228:12)
>     at /Users/gdad-s-river/.meteor/packages/meteor-tool/.1.1.13-modules.8.c2mc9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/promise/node_modules/meteor-promise/fiber_pool.js:33:40

The blaze-template todos as well as react-meteor todo example work fine on the android device. Help please? I'm fairly new to Meteor and React, but I know the basics, am I missing something here?

**Comment by tomasz-szymanek** [comment]
+1

**Comment by tmeasday** [comment]
Have you tried the `react` branch of https://github.com/meteor/todos ? This repository is a little out of date now. Could you please try there and open an issue on that repo if you still see there?

**Comment by stubailo** [comment]
(Should we delete this repo, or maybe just empty it out with a link to the branch?)
